suite: spatial
checkpoint: openvla/openvla-7b-finetuned-libero-spatial
output_dir: /root/autodl-tmp/eval_logs/openvla
center_crop: true
suites:
  spatial: {task_suite: libero_spatial, checkpoint: openvla/openvla-7b-finetuned-libero-spatial}
  object: {task_suite: libero_object, checkpoint: openvla/openvla-7b-finetuned-libero-object}
  goal: {task_suite: libero_goal, checkpoint: openvla/openvla-7b-finetuned-libero-goal}
  long: {task_suite: libero_10, checkpoint: openvla/openvla-7b-finetuned-libero-10}
