dataset:
  root: /root/piper_record_test
  repo_id: local/piper_record_test
policy:
  type: act
  device: cuda
  push_to_hub: false
training:
  output_dir: /root/outputs/train/act_piper_test
  reference_checkpoint_step: 20000
  reference_checkpoint: /root/outputs/train/act_piper_test/checkpoints/020000/pretrained_model
  steps: 20000
  batch_size: default_from_lerobot
  save_freq: default_from_lerobot
  wandb: false
