allow_robot_execution: false
allow_shared_checkpoint: false
can_interface: can0
bitrate: 1000000
front_camera: 0
wrist_camera: 2
device: cuda
control_hz: 15
total_timeout_s: 100
handoff_timeout_s: 30
skills:
  a:
    checkpoint: $HOME/lerobot_work/models/act_banana_plate_20000/pretrained_model
    task: Put the banana on the plate.
    completion_s: 30
    timeout_s: 35
  b:
    checkpoint: $HOME/lerobot_work/models/act_block_storage_20000/pretrained_model
    task: Put the block in the storage box and return to Home Pose.
    completion_s: 30
    timeout_s: 35
safety:
  action_dim: 7
  lower_bounds: [-95, -95, -95, -95, -95, -95, 0]
  upper_bounds: [95, 95, 95, 95, 95, 95, 100]
  max_step_delta: [2, 2, 2, 2, 2, 2, 4]
